### ISSUE TITLE
Multiple Clocks

### ISSUE THREAD

**Issue by carlfmichel** [longshotlabs/meteor-reactive-clock#3]
In my quest to learn Meteor I'm trying to build a simple stopwatch app. So I have multiple projects that I want to track time to. Each project needs its own timer/clock. Could I use to this package to tie individual timers to each project and update those times to the server?

**Comment by aldeed** [comment]
You probably could use it but not quite in the way you describe. I think you would just store a `startTime` in the database when they click "Start" for a project timer, and then you would use this package only for displaying the elapsed time reactively in the browser. To do that you'd do something like

``` js
Template.myTimerPage.onCreated(function () {
  this.clock = new ReactiveClock();

  this.autorun(() => {
    let project = Projects.findOne(someId);
    let elapsed = (Date.now() - project.startTime.getTime()) / 1000;
    this.clock.setElapsedSeconds(elapsed);
  });

  this.clock.start();
});

Template.myTimerPage.helpers({
  displayTime: () => {
    return Template.instance().clock.elapsedTime({format: '00:00:00'});
  }
});
```
