### ISSUE TITLE
Persisten clock?

### ISSUE THREAD

**Issue by 0xbs0d** [longshotlabs/meteor-reactive-clock#4]
HI,

I've been trying to get this to work for a couple of days but it seems that I'm stuck. I'm missing something. I have two buttons on screen which just simply start and stop the clock (ExerciseClock01.start()/stop()) and I'm updating the elapsed time in the database every second. I save the state when the page is destroyed and re-read it once it's realoded. All that works fine. But when I fire the start() again it just resets the clock to 0 and obviously updates the database. I'm missing something somewhere. I tried to set the elapsedtime on the click event without any success. Do you have an idea what I might be doing wrong and at least point me in the right direction? 
Thank you!

**Comment by aldeed** [comment]
This was designed for non-persistent (persists after a hot reload, but not after a page refresh). However, I think it should work as long as you do `ExerciseClock01.setElapsedSeconds(valueFromDB)` before you do `start()` for the first time.
